version: "2"
volumes:
  mysql:
    external: true
services:
  mysql:
    image: mysql:8.0.17
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=bundys
      - MYSQL_DATABASE=bundys
    volumes:
      - mysql:/var/lib/mysql
    #ports:
    #  - 3306:3306
    command:
      - '--default-authentication-plugin=mysql_native_password'
      - '--skip-mysqlx'

  bundys-api:
    image: bundys-api:latest
    container_name: bundys-api
    ports:
      - 6060:6060
    command:
      - '--sql-db-host=mysql'

  bundys-gui:
    image: httpd:2.4
    container_name: bundys-gui
    volumes:
      - $PWD/gui/:/usr/local/apache2/htdocs/
    ports:
      - 8080:80
